language: node_js
branches:
  except:
    - gh-pages
node_js:
  - 4
  - 6
  - 8
before_script:
  - npm run build
script:
  - npm run cover:schema
after_success:
  - npm run cover:up
notifications:
  email: false
